### ISSUE TITLE
`startswith`/`endswith` values contains extra `'`

### ISSUE THREAD

**Issue by barvhaim** [nNipsx-Sec/pySigma-backend-qradar#10]
Translating a rule which contains startswith or endswith, for example
`Image|endswith: 'schtasks.exe'` 
gets extra `'` on the inner value, 
`"Image" ILIKE '%'schtasks.exe''`

I am facing the same issue with the backend I am building, is it the correct behavior from pySigma or do we miss any flag?

**Comment by nnipsxz** [comment]
Thanks. I'll check this

**Comment by nNipsx-Sec** [comment]
Fixed in version 0.3.0
