### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by fabaff** [nNipsx-Sec/pySigma-backend-qradar#9]
- `version = "0.8.1"` : https://github.com/nNipsx-Sec/pySigma-backend-qradar/blob/main/poetry.lock#L94
- `pysigma = "^0.7.2"` : https://github.com/nNipsx-Sec/pySigma-backend-qradar/blob/main/pyproject.toml#L13

**Comment by nNipsx-Sec** [comment]
Yes, i'll fix and update in tomorrow, everything now is already

**Comment by fabaff** [comment]
Thanks

**Comment by nNipsx-Sec** [comment]
https://github.com/nNipsx-Sec/pySigma-backend-qradar/releases/tag/v0.2.1

I have update this issue with new version. Please check it and if resolve  please close this issue.

Thanks
